miniproject2/Models/Domain/student.cs
namespace miniproject2.Models.Domain
{
	public class student
	{
		public Guid Id { get; set; }
		public string Name { get; set; }
		public string Email { get; set; }

		public string course { get; set; }
		public double percentage { get; set; }
	}
}

miniproject2/Models/ErrorViewModel.cs
namespace miniproject2.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

miniproject2/Models/addstudentviewmodel.cs
namespace miniproject2.Models
{
    public class addstudentviewmodel
    {
        public string Name { get; set; }
        public string Email { get; set; }

        public string course { get; set; }
        public double percentage { get; set; }
    }
}

miniproject2/Models/updatestudentview model.cs
namespace miniproject2.Models
{
	public class updatestudentview_model
	{
		public Guid Id { get; set; }
		public string Name { get; set; }
		public string Email { get; set; }

		public string course { get; set; }
		public double percentage { get; set; }
	}
}

miniproject2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using miniproject2.Models;
using System.Diagnostics;

namespace miniproject2.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

miniproject2/Controllers/studentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using miniproject2.Models;
using miniproject2.Models.Domain;
using miniproject2.studentdata;

namespace miniproject2.Controllers
{
    public class studentController : Controller
	{
        private readonly studentcontext mvcstudentcontext;

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var student = await mvcstudentcontext.students.ToListAsync();
            return View(student);
        }
        public studentController(studentcontext mvcstudentcontext)
        {
            this.mvcstudentcontext=mvcstudentcontext;
        }

        [HttpGet]
		public IActionResult Add()
		{
			return View();
		}
        [HttpPost]

        public async Task<IActionResult> Add(addstudentviewmodel addstudentRequest)
        {
            var students = new student()
            {
                Id= Guid.NewGuid(),
                Name=addstudentRequest.Name,
                Email=addstudentRequest.Email,
                course=addstudentRequest.course,
                percentage=addstudentRequest.percentage
            };
            await mvcstudentcontext.students.AddAsync(students);
            await mvcstudentcontext.SaveChangesAsync();
            return RedirectToAction("Add");
        }
        public async Task<IActionResult> view(Guid id)
        {
             var student=await mvcstudentcontext.students.FirstOrDefaultAsync(x => x.Id==id);
            if (student !=null)
            {
                var viewmodel = new updatestudentview_model()
                {
                    Id= student.Id,
                    Name=student.Name,
                    Email=student.Email,
                    course=student.course,
                    percentage=student.percentage

                };
                return View(viewmodel);
            }
            

			return RedirectToAction("Index");
        }
    }
}

miniproject2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

miniproject2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - miniproject2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/miniproject2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">miniproject2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*< li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="student" asp-action="Add">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="student" asp-action="View">Edit</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - miniproject2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

miniproject2/Views/student/Add.cshtml
@model miniproject2.Models.addstudentviewmodel
@{
}
<h1>Student Registeration</h1>
<form method="post" action="Add" class="mt-5">
    <div class="form-group">
        <label for="">Name</label>
        <input type="text" class="form-control" asp-for="Name" >
    </div>

    <div class="form-group">
        <label for="">Email</label>
        <input type="email" class="form-control" asp-for="Email">
    </div>

    <div class="form-group">
        <label for="">Course Name</label>
        <input type="text" class="form-control" asp-for="course">
    </div>

    <div class="form-group">
        <label for="">Percentage</label>
        <input type="number" class="form-control" asp-for="percentage">
    </div>

    <button type="submit" class="btn btn-primary">Register</button>

    </form>

miniproject2/Views/student/Index.cshtml
@model List<miniproject2.Models.Domain.student>
@{
}

<h1>Students</h1>
<table class="table">
	<thead>
		<tr>
			<th> Id </th>
			<th> Name</th>
			<th> Email </th>
			<th> Course Name </th>
			<th> Percentage </th>
		</tr>
	</thead>
	<tbody>
		@foreach (var studen in Model)
		{
			<tr>
				<td>@studen.Id</td>
				<td>@studen.Name</td>
				<td>@studen.Email</td>
				<td>@studen.course</td>
				<td>@studen.percentage</td>
			</tr>
		}
	</tbody>

</table>

miniproject2/Views/student/view.cshtml
@model miniproject2.Models.updatestudentview_model
@{
}
<h1> Edit Student Registeration</h1>
<form method="post" action="view" class="mt-5">
    div class="form-group">
    <label for="">Id</label>
    <input type="text" class="form-control" asp-for="Id" readonly>
    </div>
    <div class="form-group">
        <label for="">Name</label>
        <input type="text" class="form-control" asp-for="Name">
    </div>

    <div class="form-group">
        <label for="">Email</label>
        <input type="email" class="form-control" asp-for="Email">
    </div>

    <div class="form-group">
        <label for="">Course Name</label>
        <input type="text" class="form-control" asp-for="course">
    </div>

    <div class="form-group">
        <label for="">Percentage</label>
        <input type="number" class="form-control" asp-for="percentage">
    </div>

    <button type="submit" class="btn btn-primary">Register</button>

</form>